version: '3'

services: 
    websocket-web:
        build: web
        ports: 
            - "8080:80"
            - "8443:443"
    websocket-plain:
        build: server
        ports:
            - "8081:8080"
            - "8082:8081"
        environment: 
            - "SECURE=FALSE"
    websocket-secure:
        build: server
        ports:
            - "8083:8080"
            - "8084:8081"
        environment: 
            - "SECURE=TRUE"